---
title: "Clustering differences"
Author: Kat Moore
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: no
    df_print: paged
    highlight: kate
    canon: true
params:
  dds: "data/rnaseq/processed/08_dds_ovr_inv_vs_rest.Rds"
  dds.old: "/DATA/share/postpartumbc/data/Rds/08_ape_ovr_inv_vs_rest.Rds"
  vsd.old: "/DATA/share/postpartumbc/data/Rds/08_vsd_ovr.Rds"
  igclust: "results/rnaseq/clustering/11_inv_clusters.xlsx"
  old_igclust: "/DATA/share/postpartumbc/results/clustering/11_inv_clusters.xlsx"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(DESeq2)
library(conflicted)
conflict_prefer("filter", "dplyr")
```

Per Hanne's requests

```{r}
#here(params$igclust) %>% readxl::excel_sheets()
clust <- readxl::read_excel(here(params$igclust), sheet = "col_clusters")
```

```{r}
old.clust <- readxl::read_excel(here(params$old_igclust), sheet = "col_clusters")
```

```{r}
clust_summary <- full_join(select(clust, sample_name, clust.new = IG_col_cluster, study_group),
          select(old.clust, sample_name, clust.old = IG_col_cluster),
          by = "sample_name")  %>%
  relocate(study_group, .after=sample_name)

clust_summary
```

```{r}
table(clust_summary$study_group, clust_summary$clust.new) %>%
  addmargins()
```

```{r}
table(clust_summary$study_group, clust_summary$clust.old) %>%
  addmargins()
```

```{r}
clust_summary %>%
  dplyr::filter(clust.new != clust.old)
```

```{r}
dds <- readRDS(here(params$dds))
```

```{r}
sd <- colData(dds) %>%
  as.data.frame() 

sd %>%
  dplyr::filter(sample_name == "ppbc_inv_139") %>%
  select(sample_name,patient_ID, study_group, batch, time_OS_months,death,
         time_DRS_months, distant_recurrence)

```

```{r}
vsd.old <- readRDS(params$vsd.old)

sd.old <- colData(vsd.old) %>%
  as.data.frame() 

sd.old %>%
  dplyr::filter(sample_name == "ppbc_inv_139") %>%
  select(sample_name, patient_ref, study_group, batch, overall_survival, months_overall_survival,
         distant_recurrence, months_to_drs)
```

```{r}
sd.comp <- full_join(
  sd %>% select(sample_name, batch.new = batch, timeOS.new=time_OS_months, death.new=death,
                DR.new = distant_recurrence, timeDR.new=time_DRS_months),
  sd.old %>% select(sample_name, batch.old=batch,timeOS.old = months_overall_survival,
                  death.old=overall_survival, timeDR.old=months_to_drs, DR.old=distant_recurrence),
  by="sample_name")
```

```{r}
sd.comp[,order(colnames(sd.comp))] %>%
  relocate(sample_name,.before = everything())
```


```{r}
sd.comp %>%
  dplyr::filter(DR.new != DR.old)
```

```{r}
sd.comp %>%
  dplyr::filter(timeDR.new != timeDR.old)
```

```{r}
sd.comp %>%
  dplyr::filter(DR.new != DR.old)
```

```{r}
sd.comp %>%
  dplyr::filter(death.new != death.old)
```

```{r}
sd.comp %>%
  select(sample_name, batch.new, batch.old) %>%
  mutate(batch.new = as.character(str_remove(as.character(batch.new), "batch ")),
         batch.old = str_remove(as.character(batch.old),".0")) %>%
  dplyr::filter(batch.new != batch.old)
```
