---
title: "Importing the data"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    df_print: paged
    toc: yes
  pdf_document:
    toc: yes
---

# Loading Packages 

```{r}
#install.packages("tidyverse")
library(tidyverse)
library(readxl)
#if (!requireNamespace("BiocManager", quietly = TRUE))
   # install.packages("BiocManager")
#BiocManager::install("tximport")
library(tximport)
#install.packages("here")
library(here)
library(dplyr)
library(tidyr)
```

```{r}
getwd()
```

# Importing the data

```{r}
PPBC_metadata <- read_excel("PPBC_metadata.xlsx", sheet = "patient_data")
```

```{r}
colnames(PPBC_metadata)
```


# Data structure

```{r}
str(PPBC_metadata)
```


# Subsetting the data into categories only containing certain study groups! 

```{r}
Data_inv_vs_npbc <- subset(PPBC_metadata, study_group %in% c("ppbcpw","npbc"), )

Data_inv_vs_prbc <- subset(PPBC_metadata, study_group %in% c("ppbcpw","prbc"), )

Data_inv_vs_lac <- subset(PPBC_metadata, study_group %in% c("ppbcpw","ppbcdl"), )

Data_prbc_vs_npbc <- subset(PPBC_metadata, study_group %in% c("prbc","npbc"), )

Data_inv <- subset(PPBC_metadata, study_group == "ppbcpw", )

Data_lac <- subset(PPBC_metadata, study_group == "ppbcdl", )

Data_prbc <- subset(PPBC_metadata, study_group == "prbc", )

Data_npbc <- subset(PPBC_metadata, study_group == "npbc", )

Data_IG_low <- subset(PPBC_metadata, IG_ID_short == "low", )
Data_IG_high <- subset(PPBC_metadata, IG_ID_short == "high", )

Data_TAPC_low <- subset(PPBC_metadata, TAPC == "low", )
Data_TAPC_high <- subset(PPBC_metadata, TAPC == "high", )

Data_plasmaB_low <- subset(PPBC_metadata, Plasma_ID_short == "low", )
Data_plasmaB_high <- subset(PPBC_metadata, Plasma_ID_short == "high", )

Data_TCD38_low <- subset(PPBC_metadata, TI_CD38 == "low", )
Data_TCD38_high <- subset(PPBC_metadata, TI_CD38 == "high", )

Data_SCD38_low <- subset(PPBC_metadata, SI_CD38 == "low", )
Data_SCD38_high <- subset(PPBC_metadata, SI_CD38 == "high", )
```



# Saving the data files

```{r}
saveRDS(PPBC_metadata, file = "PPBC_metadata.RDS") 
saveRDS(Data_inv_vs_npbc, file = "Data_inv_vs_npbc.RDS") 
saveRDS(Data_inv_vs_prbc, file = "Data_inv_vs_prbc.RDS") 
saveRDS(Data_inv_vs_lac, file = "Data_inv_vs_lac.RDS")
saveRDS(Data_prbc_vs_npbc, file = "Data_prbc_vs_npbc.RDS") 
saveRDS(Data_inv, file = "Data_inv.RDS") 
saveRDS(Data_lac, file = "Data_lac.RDS") 
saveRDS(Data_prbc, file = "Data_prbc.RDS") 
saveRDS(Data_npbc, file = "Data_npbc.RDS") 
saveRDS(Data_IG_low, file = "Data_IG_low.RDS") 
saveRDS(Data_IG_high, file = "Data_IG_high.RDS") 
saveRDS(Data_TAPC_low, file = "Data_TAPC_low.RDS") 
saveRDS(Data_TAPC_high, file = "Data_TAPC_high.RDS") 
saveRDS(Data_plasmaB_low, file = "Data_plasmaB_low.RDS") 
saveRDS(Data_plasmaB_high, file = "Data_plasmaB_high.RDS") 
saveRDS(Data_TCD38_low, file = "Data_TCD38_low.RDS") 
saveRDS(Data_TCD38_high, file = "Data_TCD38_high.RDS") 
saveRDS(Data_SCD38_low, file = "Data_SCD38_low.RDS") 
saveRDS(Data_SCD38_high, file = "Data_SCD38_high.RDS") 
```







