# All in millimeters
resolution: 0.01
minimum_density: 1.0
tissues:
    tumor:
        kernel_bandwith: 0.001
        cell_types:
            - "PanCK+"
        weight: 1 #Per square mm there should be at least this many tumor cell(s)
    stroma:
        kernel_bandwith: 0.001
        cell_types:
            - "Other"
        weight: 0.25 # Density of stroma cells should be 4 times the density of tumor for a pixel to be called as Stroma.
