---
title: "All comparison overview"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)

```

```{r}
ddsLRT = readRDS(here("data", "Rds","06_ddsLRT_standard.Rds"))
repLRT = readRDS(here("data", "Rds", "06_repLRT.Rds"))
```


```{r}
source(here("src", "deseq_report_functions.R"))
```


```{r}
gene_report = function(list_reports, ensembl_id, pthresh = 0.05, abslogfcthresh = 0.5){

  require(tidyverse)

  #print(paste("Adjusted p value threshold:", pthresh, ", abs(log2FoldChange) threshold:", abslogfcthresh))

  comp = lapply(list_reports,
                function(x) x[x$ensembl_gene_id==ensembl_id,
                              c("ensembl_gene_id","gene_name","log2FoldChange","padj")]) %>%
    unlist() %>% enframe() %>% separate(name, into = c("comparison", "field"), sep="\\.") %>%
    spread(key=field, value=value) %>%
    mutate(log2FoldChange = as.numeric(log2FoldChange),
           padj = as.numeric(padj),
           padj_cutoff = !!pthresh,
           absLog2FoldChange_cutoff = !!abslogfcthresh)

  comp = comp %>% mutate(sig = (padj < !!pthresh) & (abs(log2FoldChange) > !!abslogfcthresh)) %>%
    select(comparison, sig, padj, log2FoldChange, everything())

  return(comp)
}
```


```{r}
pw <- here("results", "diffex", "07_pairwise_comparisons_allgenes.xlsx") %>% 
  readxl::excel_sheets() %>% 
  set_names() %>% 
  map(readxl::read_excel, path = here("results", "diffex", "07_pairwise_comparisons_allgenes.xlsx"))

ovr = here("results", "diffex", "08_one_vs_rest_allgenes.xlsx") %>% 
  readxl::excel_sheets() %>% 
  set_names() %>% 
  map(readxl::read_excel, path = here("results", "diffex", "08_one_vs_rest_allgenes.xlsx"))
```

Pairwise comparisons are "x_y", one vs rest comparisons are "x_rest"

```{r}
res_list = append(pw, ovr)
names(res_list) = str_remove_all(str_remove_all(names(res_list), "rep_"), "_all")
names(res_list)
```



## CD20

Example for CD20 (official name MS4A1 ENSG00000156738)

```{r}
gene_report(res_list, "ENSG00000156738") %>% arrange(padj)
```

```{r}
plot_gene_beehive(ddsLRT, result_df = repLRT$annotated_results[repLRT$annotated_results$ensembl_gene_id == "ENSG00000156738",])
```


## NFKB1

ENSG00000109320

```{r}
gene_report(res_list, "ENSG00000109320") %>% arrange(padj)
```

```{r}
plot_gene_beehive(ddsLRT, result_df = repLRT$annotated_results[repLRT$annotated_results$ensembl_gene_id == "ENSG00000109320",])
```


## Androgen receptor

AR ENSG00000169083
```{r}
gene_report(res_list, "ENSG00000169083") %>% arrange(padj)
```

```{r}
plot_gene_beehive(ddsLRT, result_df = repLRT$annotated_results[repLRT$annotated_results$ensembl_gene_id == "ENSG00000169083",])
```


## JChain

```{r}
gene_report(res_list,"ENSG00000132465")
```


```{r}
plot_gene_beehive(ddsLRT, result_df = repLRT$annotated_results[repLRT$annotated_results$ensembl_gene_id == "ENSG00000132465",])
```

