---
title: "Marker correction"
author: "Kat Moore"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    df_print: paged
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
ggplot2::theme_set(ggplot2::theme_bw())
```

```{r libraries}
library(fs)
library(here)
library(tidyverse)
```

## Check correction of double positivity

For "impossible" combinations of immune markers, consider the cell positive for the marker with the highest expression.

```{r define_imposible_pairs}
source(here('src/spatial/call_cell_types.R'))
print(disallowed_marker_pairs)
```

Although not canonical, FoxP3+CD8+ T-cells [do exist](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4397865/) (and these cells are often CD25+.

```{r load-results}
mpif26_corrected <- readRDS(here("data/vectra/processed/objects_MPIF26.Rds"))
mpif27_corrected <- readRDS(here("data/vectra/processed/objects_MPIF27.Rds"))
```

Sanity checks

```{r}
print(disallowed_marker_pairs)
for(i in 1:length(disallowed_marker_pairs)){
  m1 <- paste0(disallowed_marker_pairs[[i]][1], "_positive")
  m2 <- paste0(disallowed_marker_pairs[[i]][2], "_positive")
  if (!(m1 %in% colnames(mpif26) & m2 %in% colnames(mpif26))) {
    next
  }
  stopifnot(nrow(dplyr::filter(mpif26_corrected, .data[[m1]] & .data[[m2]]))==0)
}
```

```{r}
for(i in 1:length(disallowed_marker_pairs)){
  m1 <- paste0(disallowed_marker_pairs[[i]][1], "_positive")
  m2 <- paste0(disallowed_marker_pairs[[i]][2], "_positive")
  if (!(m1 %in% colnames(mpif26) & m2 %in% colnames(mpif26))) {
    next
  }
  stopifnot(nrow(dplyr::filter(mpif27_corrected, .data[[m1]] & .data[[m2]]))==0)
}
```
