---
title: "Density outcomes"
author: "Kat Moore"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    df_print: paged
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(ggpubr)

theme_set(theme_bw())
```

## Load data

```{r}
mpif26 <- read_tsv(here("results/spatial/density/MPIF26.tsv"))
head(mpif26)
```

```{r}
mpif27 <- read_tsv(here("results/spatial/density/MPIF27.tsv"))
head(mpif27)
```

```{r}
density <- bind_rows(mpif26, mpif27)
```


```{r}
meta <- read_csv(here("data/metadata/spatial/00_vectra_metadata.csv"))
head(meta)
```

```{r}
dens <- meta %>%
  select(t_number, extern_number, staining, patient_ref:months_of_followup) %>%
  left_join(density, ., by = c("t_number", "panel"="staining"))
```

```{r}
head(dens)
```

```{r}
dens <- dens %>%
  mutate(classifier_label = factor(classifier_label,
                                   levels = c("Stroma", "Tumor")),
         panel = factor(panel, levels = c("MPIF26", "MPIF27")),
         study_group = factor(study_group, 
                              levels = c("nulliparous", "pregnant", "involuting")))
```


## By study group

KW or Wilcox

```{r}
dens$cell_type %>% unique()
```

```{r}
kw_density <- function(df = dens,
                       panel = c("MPIF26", "MPIF27"),
                       cell_type, colorby){
  
  stopifnot(cell_type %in% unique(df$cell_type))
  
  df <- filter(df, panel == {{panel}})
  df <- df %>% filter(cell_type == {{cell_type}})
  #tibble(
  #  cell_type = {{cell_type}},
  #  panel = {{panel}},
  #  kruskal_p = kruskal.test(PPBC ~ density, data = df)$p.value
  #)
  
  
  #pairwise.wilcox.test(df$density, df$PPBC,
  #               p.adjust.method = "BH")#$p.value %>%
    #as.data.frame() %>%
    #rownames_to_column()
  
  comps <- list(c("nulliparous", "pregnant"),
                c("nulliparous", "involuting"),
                c("pregnant", "involuting")
                )
  
  df %>%
    ggplot(aes(x = PPBC, y = density)) +
    geom_boxplot(alpha = 0) +
    geom_jitter(aes(color = get(colorby)), height = 0 ) +
    facet_wrap(~classifier_label) +
    labs(color = colorby, y = paste({{cell_type}}, "density")) +
    #stat_compare_means() #KW test all samples
    stat_compare_means(comparisons = comps) +#pairwise
    ggtitle(paste({{panel}}, {{cell_type}}))
  }

#Testing
kw_density(panel = "MPIF26", cell_type = "FoxP3+", colorby = "clin_subtype")
```

MPIF26

```{r}
lapply(unique(filter(dens, panel == "MPIF26")$cell_type),
       function(x) {
         kw_density(panel = "MPIF26", cell_type = x, colorby = "clin_subtype")
       })
```

MPIF27

```{r}
lapply(unique(filter(dens, panel == "MPIF27")$cell_type),
       function(x) {
         kw_density(panel = "MPIF27", cell_type = x, colorby = "clin_subtype")
       })
```

## Cox regression