---
title: "Spatstat"
author: "Tycho Bismeijer"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
    df_print: paged
    highlight: kate
---

```{r preliminaries, include=F}
library(conflicted)

ggplot2::theme_set(ggplot2::theme_bw())
```


```{r libraries, message=F}
library(broom)
library(here)
library(spatstat)
library(survival)
library(survminer)
library(tidyverse)
library(yaml)

source(here('src/spatial/outcome.R'))
```

```{r load-data-spatstat}
k_col_spec <- cols_only(
  cell_type = col_character(),
  measure = col_character(),
  model = col_character(),
  null_estimate = col_double(),
  observed_estimate = col_double(),
  radius = col_double(),
  delta_estimate = col_double())
spatstat <- list.files(here('results/spatial/k'), '*.tsv', full.names=T) %>%
  set_names() %>%
  map_dfr(read_tsv, col_types = k_col_spec, .id = 'filename') %>%
  mutate(
    cell_type = factor(cell_type),
    measure = factor(measure),
    model = factor(model)) %>%
  tidyr::extract(filename, c('sample_ID', '_slide', 'experimental_platform', 'batch_HALO'),
                 '(T[0-9]+-[0-9]+(_I+[0-9]+)?)_(MPIF[0-9]+)_(batch[0-9]+)') %>%
  select(-`_slide`)
sample_id_vars <- c('sample_ID', 'experimental_platform', 'batch_HALO')
```

```{r load-data-outcome}
outcome <- read_outcome(here('data/metadata/PPBC_metadata.xlsx'))
```

Samples with outcome but no spatstat:
```{r missing-a}
print(anti_join(outcome, spatstat, by = c('sample_ID', 'batch_HALO', 'experimental_platform')))
```

Samples with spatstat but no outcome:
```{r missing-b}
print(anti_join(spatstat, outcome, by = c('sample_ID', 'batch_HALO', 'experimental_platform')))
```

```{r filter-patients}
outcome <- dplyr::filter(outcome,
  study_group %in% c("non_prbc", "ppbc_inv"),
  stage != "stage IV")
```

## Overview of L

### L over radius

```{r l-overview, cache=T}
for (ct in levels(spatstat$cell_type)) {
  plt <- spatstat %>%
    dplyr::filter(measure == 'L', cell_type == ct) %>%
    ggplot(aes(x = radius, y = sample_ID)) +
    geom_tile(aes(fill = observed_estimate)) +
    scale_x_continuous('Radius (mm)') +
    scale_y_discrete('Sample') +
    ggtitle(paste0('L estimate of ', ct))
  print(plt)
}
```

### Histogram at radius 0.03 mm

```{r, de_hist}
inner_join(outcome, spatstat, by = sample_id_vars) %>%
  dplyr::filter(
    radius == 0.03,
    !is.na(death),
    !is.na(time_OS_months),
    !is.na(delta_estimate)) %>%
  group_by(cell_type, measure, model, radius) %>%
  group_walk(function (df_group, key) {
    plt <- ggplot(df_group, aes(x = delta_estimate)) +
      geom_histogram() +
      ggtitle(paste0(names(key), '=', map_chr(key, as.character), collapse = ' '))
    print(plt)
  })
```

## Comparison between groups ##

```{r compare-groups, message=F}
non_par_test <- function(x, y) {
  valid_obs <- is.finite(x) & is.finite(y)
  x <- x[valid_obs]
  y <- factor(y[valid_obs])
  if (min(table(y) < 2) | length(levels(y)) != 2) {
    str(y)
    tibble()
  } else {
    tidy(wilcox.test(x ~ y))
  }
}


inner_join(outcome, spatstat, by = sample_id_vars) %>%
  dplyr::filter(radius == 0.03) %>%
  group_by(cell_type, measure, model, radius) %>%
  summarize(non_par_test(delta_estimate, study_group)) #%>%
#  group_by(cell_type, measure, model) %>%
#  mutate(fdr_per_ct = p.adjust(p.value, 'fdr')) %>%
#  ungroup() %>%
#  mutate(fdr = fdr_per_ct / n_distinct(cell_type, measure, model))
```



## Cox-models ##

```{r fit-cox, cache=T}
fit_cox <- function(survival, predictor) {
  model <- coxph(survival ~ predictor)
  model_summary <- summary(model)
  tibble(
    loglikelihood = model$loglik[2],
    n_event = model$nevent,
    statistic_lr = model_summary$logtest[1],
    p_lr = model_summary$logtest[3],
    statistic_score = model_summary$sctest[1],
    statistic_p = model_summary$sctest[3],
    statistic_wald = model_summary$waldtest[1],
    p_wald = model_summary$waldtest[3],
    nominal_p = model_summary$coefficients[1, 5],
    hr = model_summary$conf.int[1, 1],
    hr_min = model_summary$conf.int[1, 3],
    hr_max = model_summary$conf.int[1, 4])
}

cox_results <- inner_join(outcome, spatstat, by = sample_id_vars) %>%
  group_by(cell_type, measure, model, radius) %>%
  summarize(
    fit_cox(Surv(time = time_OS_months, event = death), delta_estimate),
    n = n(),
    n_samples = n_distinct(sample_ID),
    n_data = sum(!is.na(delta_estimate)),
    .groups = 'drop')
```

```{r}
cox_results <- cox_results %>%
  group_by(cell_type, measure, model) %>%
  mutate(fdr_per_ct = p.adjust(nominal_p, 'fdr')) %>%
  ungroup() %>%
  mutate(fdr = fdr_per_ct / n_distinct(cell_type, measure, model))
cox_results
```

```{r, fig.height=20, fig.width=10}
plt <- cox_results %>%
  ggplot(aes(x=radius, y=hr, group='')) +
  geom_ribbon(aes(ymin=hr_min, ymax=hr_max), fill = 'grey70') +
  geom_line(aes(color=!is.na(fdr) & fdr < 0.05)) +
  facet_grid(rows = vars(cell_type), cols = vars(model, measure)) +
  scale_y_continuous(trans = scales::log_trans(base=2)) + 
  geom_hline(yintercept=1.0)
print(plt +
  coord_cartesian(ylim = c(1/50, 50), xlim = c(0, 1.0)))
print(plt +
  coord_cartesian(ylim = c(1/10, 10), xlim = c(0, 0.1)))
```

## Kaplan-Meier ##

Difficult to first generate kaplan-meier estimates before plotting because of limitations in
survfit and ggsurvplot, resultign in ggsurvplot needing the original data.

```{r}
inner_join(outcome, spatstat, by = sample_id_vars) %>%
  dplyr::filter(
    radius == 0.03,
    !is.na(death),
    !is.na(time_OS_months),
    !is.na(delta_estimate)) %>%
  group_by(cell_type, measure, model, radius) %>%
  group_walk(function (df_group, key) {
    df_group$de_split <- df_group$delta_estimate > median(df_group$delta_estimate, na.rm=T)
    fit = survfit(Surv(time = time_OS_months, event = death) ~ de_split, data = df_group)
    plt <- ggsurvplot(fit, data = df_group, risk.table = T, conf.int = T) +
      ggtitle(paste0(names(key), '=', map_chr(key, as.character), collapse = ' '))
    print(plt)
  })
```
