---
title: "Cibersort Figures"
author: "Kat Moore"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: yes
    df_print: tibble
    highlight: kate
params:
    figuredata: "data/figures/00_figuredata.Rds"
    boxplot_cd8: "figures/Fig4b_cibersort_CD8_boxplot.pdf"
    km_cd8: "figures/Fig4c_cibersort_CD8_km.pdf"
    rt_km_cd8: "figures/Fig4c_risktable.csv"
    boxplot_b_subtypes: "figures/supfigs/Supfig12b_boxplot_cibersort_B_subtypes.pdf"
---

## Dependencies

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(ggpubr)
library(survival)
library(survminer)
library(ggrepel)
library(ggcorrplot)
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("count", "dplyr")
conflict_prefer("rename", "dplyr")

theme_set(theme_bw())
```

## Load data

```{r}
figuredata <- readRDS(here(params$figuredata))

head(figuredata)
```

## Colors

```{r}
study_colors <- c("NP-BC"="#521262", "Pr-BC"="#AA96DA",
                  "PP-BCdl"="#112D4E", "PP-BCpw"="#46CDCF")
```

## Cibersort CD8 boxplot

```{r}
boxplot_cd8 <- figuredata %>%
  filter(!is.na(CD8_fraction)) %>%
  ggplot(aes(x = study_group, y = CD8_fraction)) +
  geom_jitter(aes(color = study_group), height = 0, width = 0.15) +
  geom_boxplot(alpha = 0) +
  scale_color_manual(values = study_colors) +
  stat_compare_means(method = "wilcox.test", comparisons = list(
    c("PP-BCpw", "Pr-BC"),
    c("PP-BCpw", "NP-BC")
  )) +
  stat_compare_means(label.y = 0.2) +
  xlab("Study group") + ylab("Relative CibersortX Fraction") +
  labs(color = "Study group")

boxplot_cd8
```

### Save output

```{r}
figureDir <- file.path(here("figures"))
dir.create(figureDir, showWarnings = F)
pdf(file = here(params$boxplot_cd8), width = 10, height = 7)
boxplot_cd8
dev.off()
```

## KM CD8 Cibersort


```{r}
figuredata %>%
  filter(!is.na(CD8_cat)) %>%
  group_by(CD8_cat, study_group) %>% count() %>%
  pivot_wider(names_from = CD8_cat, values_from = n, values_fill = 0)
```

Due to power issues, omit lac. High/low is around the median density.

```{r}
CD8_km <- function(df, event_type = c("OS", "DRS"), returndata = F){
  
event_type <- match.arg(event_type)
  
  df <- df %>% 
    dplyr::filter(
      study_group %in% c("PP-BCpw", "Pr-BC", "NP-BC"),
      !is.na(CD8_cat)
    ) %>%
    #The CD8 category is also CD3 pos, see the spatial pipeline
    rename(CD8_CD3 = CD8_cat)
  
  df <- df[,c("CD8_CD3", "study_group", "sample_name", "time_OS_months", "death",
              "reason_death", "time_DRS_months", "distant_recurrence")]
  
  if(returndata){return(df)}
  
  if(event_type == "OS"){
    df <- df %>% filter(!is.na(death), !is.na(time_OS_months)) %>%
      filter(time_OS_months > 20 | reason_death == "BC") %>%
      as.data.frame()
    y <- "Overall survival"
    fit <- survfit(Surv(time=time_OS_months, event=death) ~ study_group + CD8_CD3, data = df)
  } else {
    df <- df %>% filter(!is.na(distant_recurrence), !is.na(time_DRS_months)) %>%
      filter(time_DRS_months > 20 | reason_death == "BC") %>%
      as.data.frame()
    y <- "Distant recurrence"
    fit <- survfit(Surv(time=time_DRS_months, event=distant_recurrence) ~ study_group + CD8_CD3, data = df)
  }
  
  ggsurvplot(
    fit, data = df,
    xlab = "Months", 
    ylab = paste(y,"probability"),
    #title = paste(y, cell, "stratified by median density:", signif(med, 2)),
    palette = study_colors[names(study_colors) %in% unique(df$study_group)],
    ggtheme = theme_bw(),
    pval = T,
    facet.by = "CD8_CD3",
    legend.title="Study group:"
  )
}

km_cd8 <- CD8_km(figuredata, event_type = "OS", returndata = F)
km_cd8
```

### Risk table

```{r, fig.height=7, fig.width=12}
risktable <- function(ggkm, response, text.size = 8){
  ggplot(ggkm$data, aes(time, study_group)) + 
    ggrepel::geom_text_repel(aes(label = n.risk)) +
    facet_wrap(as.formula(paste("~", response))) + theme_bw() + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_rect(fill="white", size = 1),
          axis.text.x = element_text(color="black", size = text.size+2),
          axis.text.y = element_text(color="black", size = text.size),
          axis.title = element_text(color="black", size = text.size+4),
          strip.text = element_text(color="black", size = text.size))+
    ggtitle("Risk Tables") +
    xlab("Time") + ylab("")
}

rt_km_cd8 <- risktable(km_cd8, response = "CD8_CD3")
rt_km_cd8
```

### Save output

```{r}
pdf(file = here(params$km_cd8), width = 12, height = 7)
km_cd8
rt_km_cd8
dev.off()
```

Also save risk table as csv.

```{r}
write_csv(km_cd8$data, here(params$rt_km_cd8))
```

## Boxplot B cell subtypes

```{r, fig.height=5, fig.width=8}
boxplot_b_subtypes <- figuredata %>%
  filter(!is.na(Plasma_fraction)) %>%
  select(study_group, Plasma_fraction, naive_B_fraction, memory_B_fraction) %>%
  pivot_longer(cols = c(Plasma_fraction, naive_B_fraction, memory_B_fraction),
               names_to = "B_subtype", values_to = "relative_fraction") %>%
  ggplot(aes(x = study_group, y = relative_fraction)) +
  facet_wrap(~B_subtype) +
  geom_jitter(aes(color = study_group), height = 0, width = 0.15) +
  geom_boxplot(alpha = 0) +
  scale_color_manual(values = study_colors) +
  stat_compare_means(method = "wilcox.test", comparisons = list(
    c("PP-BCpw", "Pr-BC"),
    c("PP-BCpw", "NP-BC")
  )) +
  stat_compare_means(label.y = 0.3) +
  xlab("Study group") + ylab("Relative CibersortX Fraction") +
  labs(color = "Study group")

boxplot_b_subtypes
```

### Save output

```{r}
supFigDir <- file.path(here("figures/supfigs"))
dir.create(figureDir, showWarnings = F)
pdf(file = here(params$boxplot_b_subtypes), width = 10, height = 7)
boxplot_b_subtypes
dev.off()
```

## Session info

```{r}
sessionInfo()
```
