---
title: "Isotype figures"
author: "Kat Moore"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: yes
    df_print: tibble
    highlight: kate
params:
    figuredata: "data/figures/00_figuredata.Rds"
    fig3a: "figures/Fig3a_boxplot_isotypes.pdf"
    fig3bc: "figures/Fig3bc_km_isotypes.pdf"
    rt_fig3bc: "figures/Fig3bc_risktable.csv"
    fig3d: "figures/Fig3d_cor_Ig_TAPC.pdf"
---

## Dependencies

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(ggpubr)
library(survival)
library(survminer)
library(RColorBrewer)
library(ggrepel)
library(conflicted)

conflict_prefer("filter", "dplyr")

theme_set(theme_bw())
```

## Load data

```{r}
figuredata <- readRDS(here(params$figuredata))
```

## Colors

```{r}
study_colors <- c("NP-BC"="#521262", "Pr-BC"="#AA96DA", "PP-BCdl"="#112D4E", "PP-BCpw"="#46CDCF")
```

## Figure 3A - Boxplot Ig expression

```{r, fig.height=6, fig.width=8}
fig3a <- figuredata %>%
  select(study_group, IgA:IgM) %>%
  pivot_longer(cols = c(IgA, IgD, IgG, IgM),
               names_to = "isotype", values_to = "normCount") %>%
  filter(!is.na(normCount)) %>%
  ggplot(aes(x = study_group, y = normCount)) +
  geom_jitter(aes(color = isotype), shape = 15, height = 0, width = 0.2) +
  geom_boxplot(alpha = 0) +
  facet_wrap(~isotype, scale = "free_y") +
  scale_colour_discrete() +
  stat_compare_means(method = "wilcox.test",
                     comparisons = list(c("PP-BCpw", "PP-BCdl"),
                                        c("PP-BCpw", "Pr-BC"),
                                        c("PP-BCpw", "NP-BC"))) +
  stat_compare_means() +
  #theme(text = element_text(size=18)) +
  ylab("Normalized Expression Levels") +
  xlab("Study group")

fig3a
```

### Save output

```{r}
figureDir <- file.path(here("figures"))
dir.create(figureDir, showWarnings = F)
pdf(file = here(params$fig3a), width = 12, height = 8)
fig3a
dev.off()
```

## Fig 3BC - IG expression KMs

Combintation figures 3B and 3C. IG expression level is split around the median. Exclude lac from RNAseq analyses due to lack of samples.

```{r}
ig_km <- function(df, event_type = c("OS", "DRS"), returndata = F){
  
  event_type <- match.arg(event_type)
  
  df <- df %>%
    filter(
      study_group %in% c("PP-BCpw", "Pr-BC", "NP-BC")
    )
  
  df <- df %>%
    select(study_group, IgA_rank:IgM_rank,
           death, time_OS_months,
           distant_recurrence, time_DRS_months) %>%
    pivot_longer(cols = c(IgA_rank:IgM_rank), names_to = "isotype",
                 values_to = "rank") %>%
    mutate(isotype = str_remove(isotype, "_rank")) %>%
    mutate(isotype_group = paste(isotype, rank)) %>%
    filter(!is.na(rank)) %>%
    droplevels()
  
  if(returndata){return(df)}
  
  # There are a lot of facets, we can either make the chart very large, or
  # Use a for loop to plot the isotypes separately

  plt <- list()

  for(ig in c("IgA", "IgD", "IgM", "IgG")){
    
    dfi <- df[df$isotype == ig,]

    if(event_type == "OS"){
      dfi <- dfi %>% filter(!is.na(death), !is.na(time_OS_months)) %>%
        as.data.frame()
      y <- "Overall survival"
      fit <- survfit(Surv(time=time_OS_months, event=death) ~ study_group + isotype_group, data = dfi)
    } else {
      dfi <- dfi %>% filter(!is.na(distant_recurrence), !is.na(time_DRS_months)) %>%
        as.data.frame()
      y <- "Distant recurrence"
      fit <- survfit(Surv(time=time_DRS_months, event=distant_recurrence) ~ study_group + isotype_group, data = dfi)
    }
    #return(fit)
    plt[[length(plt)+1]] <- ggsurvplot(
      fit, data = dfi,
      xlab = "Months", 
      ylab = paste(y,"probability"),
      palette = study_colors[names(study_colors) %in% unique(dfi$study_group)],
      ggtheme = theme_bw(),
      pval = T,
      facet.by = "isotype_group",
      legend.title="Study group:"
    )
  }
   
  names(plt) <-  c("IgA", "IgD", "IgM", "IgG")
  plt
}

fig3b <- ig_km(figuredata, event_type = "OS", returndata = F)

fig3b
```

### Risk table

```{r, fig.height=6, fig.width=9}
risktable <- function(ggkm, response, text.size = 8){
  ggplot(ggkm$data, aes(time, study_group)) + 
    ggrepel::geom_text_repel(aes(label = n.risk)) +
    facet_wrap(as.formula(paste("~", response))) + theme_bw() + 
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          strip.background = element_rect(fill="white", size = 1),
          axis.text.x = element_text(color="black", size = text.size+2),
          axis.text.y = element_text(color="black", size = text.size),
          axis.title = element_text(color="black", size = text.size+4),
          strip.text = element_text(color="black", size = text.size))+
    ggtitle("Risk Tables") +
    xlab("Time") + ylab("")
}

rt_fig3b <- lapply(names(fig3b), function(x){
  risktable(fig3b[[x]], response = "isotype_group")
}) %>% set_names(names(fig3b))
rt_fig3b
```

### Save output

```{r}
pdf(file = here(params$fig3b), width = 9, height = 6)
fig3b
rt_fig3b
dev.off()
```

Also save risk table as csv.

```{r}
write_csv(bind_rows(lapply(fig3b, function(x){x$data}), .id = "isotype"),
          here(params$rt_fig3b))
```

## Fig 3D - Correlation IgA/IgG and TAPC in PP-BCpw

```{r}
fig3d <- 
  list(
    IgA = figuredata %>%
      filter(study_group == "PP-BCpw") %>%
      filter(!is.na(TAPC_score)) %>%
      ggplot(aes(x=TAPC_score, y = IgA)) +
      geom_jitter(aes(color = as.factor(TAPC_score)), height = 0, width = 0.15) +
      geom_boxplot(alpha = 0, aes(group = TAPC_score), color = "darkgray"#, linetype="dashed"
      ) +
      geom_smooth(method = "lm", formula = y ~ x, linetype="dashed") +
      ggpubr::stat_cor(method = "kendall", label.y = 3.5, label.x = -0.2,
                       aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~"))) +
      ggtitle("Kendall's correlation IgA and TAPC in PP-BCpw") +
      xlab("TAPC score") + ylab("Normalized IgA expression") +
      labs(color = "TAPC score") +
      scale_color_brewer(palette = "Spectral"),
    
    IgD = figuredata %>%
      filter(study_group == "PP-BCpw") %>%
      filter(!is.na(TAPC_score)) %>%
      ggplot(aes(x=TAPC_score, y = IgG)) +
      geom_jitter(aes(color = as.factor(TAPC_score)), height = 0, width = 0.15) +
      geom_boxplot(alpha = 0, aes(group = TAPC_score), color = "darkgray"#, linetype="dashed"
      ) +
      geom_smooth(method = "lm", formula = y ~ x, linetype="dashed") +
      ggpubr::stat_cor(method = "kendall", #label.y = 3.5, label.x = -0.2,
                       aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~"))) +
      ggtitle("Kendall's correlation IgG and TAPC in PP-BCpw") +
      xlab("TAPC score") + ylab("Normalized IgG expression") +
      labs(color = "TAPC score") +
      scale_color_brewer(palette = "Spectral")
  )

fig3d
```

### Save output

```{r}
pdf(file = here(params$fig3d), width = 12, height = 8)
fig3d
dev.off()
```

## Session info

```{r}
sessionInfo()
```

