---
title: "Reviewer requests"
author: "Kat Moore"
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      df_print: paged
      highlight: kate
params:
    figuredata: "data/figures/00_figuredata.Rds"
    study_km: "src/figures/study_km.R"
    reviewer_requests: "figures/reviewer_requests.pdf"
---

## Dependencies

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(tinytex.verbose = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(ggpubr)
library(survival)
library(survminer)
library(ggrepel)
library(ggcorrplot)
library(conflicted)

conflict_prefer("filter", "dplyr")
conflict_prefer("rename", "dplyr")
theme_set(theme_bw())
```

```{r}
source(here("src/figures/faceted_risktable.R"))
source(here("src/figures/study_km.R"))
```

## Load data

```{r}
figuredata <- readRDS(here(params$figuredata))

head(figuredata)
```

## Colors

```{r}
levels(figuredata$study_group)
study_colors <- c("NP-BC"="#521262", "Pr-BC"="#aa96da",
                  "PP-BCdl"="#282c75", "PP-BCpw"="#46cdcf")
levels(figuredata$IG_col_cluster)
tertile_colors <- c("low"="#ffb600", "medium"="#ff7900","high"="#a10702")
```

## Functions

```{r}
cor_plot <- function(df=figuredata, x, y, colorby, met, ht = 1, wd = 0.2, rsquared=F, ...){
  
  df <- df[!is.na(df[,x]) & !is.na(df[,y]),]

  df <- df %>%
    ggplot(aes(get(x), get(y))) +
    geom_jitter(aes(color = get(colorby)), height = ht, width = wd, shape = 15) +
    geom_smooth(method = "lm", formula = y ~ x) +
    xlab(str_replace_all(x, "_", " ")) +
    ylab(str_replace_all(y, "_", " ")) +
    labs(color = str_replace_all(colorby, "_", " "))
  
  if(rsquared){
    df <- df +
      ggpubr::stat_cor(method = met, #label.y = 3.5, label.x = -0.2,
                       aes(label = paste(..rr.label.., ..r.label.., ..p.label..,
                                         sep = "~`,`~")))
  } else {
    df <-  df +
    ggpubr::stat_cor(method = met, #label.y = 3.5, label.x = -0.2,
                     aes(label = paste(..r.label.., ..p.label.., sep = "~`,`~")))
  }
  df
}
```


## CD38 and Ig mRNA

### CD38 high/low categories

```{r}
igs <- c("blue", "red","darkgreen","purple")
names(igs) <- c("IgA", "IgG", "IgM", "IgD")

tmpdf <- figuredata %>%
  rename(CD38 = TI_CD38) %>%
  filter(!is.na(CD38)) %>%
  select(CD38, IgA, IgM, IgG, IgD) %>%
  pivot_longer(cols = starts_with("Ig"), names_to = "isotype", values_to = "expression") %>%
  filter(!is.na(expression)) 

boxplot_ig_CD38 <- lapply(names(igs), function(x){
  tmpdf %>%
    filter(isotype == !!x) %>%
    ggplot(aes(x = CD38, y = expression, color = isotype)) +
    geom_point(position = position_jitter(height = 0), shape = 15) +
    geom_boxplot(alpha = 0) +
    xlab("CD38 category") + 
    stat_compare_means(method = "wilcox.test",
                       comparisons = list(c("low", "high"))) +
    #stat_compare_means() +
    ggtitle(paste("CD38+ and", x, "expression")) +
    scale_color_manual(values = igs)
  })

boxplot_ig_CD38
```

### CD38 numeric correlation

```{r}
CD38_Ig_cor_all <- lapply(c(names(igs)), function(ig){
  cor_plot(figuredata, x= "TI_CD38_total", y=ig, colorby = "study_group",
           met = "spearman", ht = 0, wd = 0.2, rsquared=F) +
    scale_color_manual(values = study_colors[names(study_colors) != "rest"]) +
    ggtitle(paste("Spearman correlation between CD38 and", ig, "in all samples"))
}) %>% set_names(igs)

CD38_Ig_cor_all
```

```{r}
CD38_Ig_cor_group <- lapply(names(igs), function(ig){
  cor_plot(figuredata, x="TI_CD38_total", y=ig, colorby = "study_group",
           met = "spearman", ht = 0, wd = 0, rsquared=F) +
    scale_color_manual(values = study_colors[names(study_colors) != "rest"]) +
    ggtitle(paste("Spearman correlation between CD38 and", ig, "by study group")) +
    facet_wrap(~study_group)
}) %>% set_names(names(igs))

CD38_Ig_cor_group
```

## TILs and TAPCs

```{r}
TIL_TAPC_cor_all <- 
  figuredata %>% filter(!is.na(TILpercent)) %>%
  cor_plot(figuredata, x= "TAPC_score", y="TILpercent", colorby = "study_group",
           met = "kendall", ht = 0, wd = 0.2, rsquared=F) +
    scale_color_manual(values = study_colors[names(study_colors) != "rest"]) +
    ggtitle("Kendall correlation between TAPCs and TILs in all samples")

TIL_TAPC_cor_all
```

```{r}
TIL_TAPC_cor_group <- 
  figuredata %>% filter(!is.na(TILpercent)) %>%
  cor_plot(figuredata, x= "TAPC_score", y="TILpercent", colorby = "study_group",
           met = "kendall", ht = 0, wd = 0.2, rsquared=F) +
  scale_color_manual(values = study_colors[names(study_colors) != "rest"]) +
  ggtitle("Kendall correlation between TAPCs and TILs per study group") +
  facet_wrap(~study_group)

TIL_TAPC_cor_group
```

## TIL Cibersort CD4

```{r}
TIL_CD4_cor_all <- 
  figuredata %>% filter(!is.na(TILpercent) & !is.na(CD4naive_fraction)) %>%
  #select("CD4")
  cor_plot(figuredata, x= "CD4naive_fraction", y="TILpercent", colorby = "study_group",
           met = "spearman", ht = 0, wd = 0, rsquared=F) +
    scale_color_manual(values = study_colors[names(study_colors) != "rest"]) +
    ggtitle("Spearman correlation between Cibersort CD3 and TILs in all samples")

TIL_CD4_cor_all
```

## TIL Cibersort CD8

```{r}
TIL_CD8_cor_all <- 
  figuredata %>% filter(!is.na(TILpercent) & !is.na(CD8_fraction)) %>%
  #select("CD4")
  cor_plot(figuredata, x= "CD8_fraction", y="TILpercent", colorby = "study_group",
           met = "spearman", ht = 0, wd = 0, rsquared=F) +
    scale_color_manual(values = study_colors[names(study_colors) != "rest"]) +
    ggtitle("Spearman correlation between Cibersort CD8 and TILs in all samples")

TIL_CD8_cor_all
```

## TIL Ig clusters

```{r}
TIL_Ig_cor_all <- 
  figuredata %>% filter(!is.na(TILpercent) & !is.na(IG_col_cluster)) %>%
  #mutate(cluster_number = as.factor(cluster_number)) %>%
  cor_plot(figuredata, x="cluster_number", y="TILpercent", colorby = "study_group",
           met = "kendall", ht = 0, wd = 0.2, rsquared=F) +
    scale_color_manual(values = study_colors[names(study_colors) != "rest"]) +
    ggtitle("Kendall correlation between Ig signature and TILs in all samples") + 
  #scale_x_discrete(labels=c("1" = "low", "2" = "medium", "3" = "high"))
  scale_x_continuous(breaks=seq(1, 3, 1)) +
  xlab("Ig gene signature")

TIL_Ig_cor_all
```

## Save output

```{r}
pdf(file = here(params$reviewer_requests), width = 12, height = 7)
TIL_CD4_cor_all
TIL_CD8_cor_all
TIL_Ig_cor_all
CD38_Ig_cor_all
CD38_Ig_cor_group
TIL_TAPC_cor_all
TIL_TAPC_cor_group
#boxplot_ig_CD38 #is this one useful?
dev.off()
```

## Session info

```{r}
sessionInfo()
```

